# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jokes_funpics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_paths', models.CharField(max_length=255)),
                ('src_url', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jokes_jokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=255)),
                ('src_url', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
