# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes_funpics',
            name='image_paths',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='jokes_funpics',
            name='src_url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jokes_jokes',
            name='src_url',
            field=models.CharField(max_length=150),
        ),
    ]
